### ISSUE TITLE
HTTPS support for embeds

### ISSUE THREAD

**Issue by pmeinhardt** [engageis/has_vimeo_video#1]
Hey, vimeo is supporting HTTPS transport for their iframe embed. It would be great to support this in order to avoid "insecure content" warnings on "https://"-pages.

[VimeoVideo#embed_url](https://github.com/engageis/has_vimeo_video/blob/731c3d59970cd3a3483b9b0e5455822c162731fe/lib/has_vimeo_video/vimeo_video.rb#L34)

Regards,
Paul

**Comment by diogob** [comment]
Great! I was also eager to implement this, I'll try to code ASAP. But feel free to send a PR :D

**Comment by pmeinhardt** [comment]
[Here it is](https://github.com/engageis/has_vimeo_video/pull/2).

**Comment by diogob** [comment]
Thanks for the PR
